#!/bin/sh

# Lists my chess results from the PGN file of my games

awk '/\[White |\[Black /{printf "%-25s", $2" "$3" "$4}/\[Result/' ~/Documents/chess/MyGames/MyGames.pgn | sed 's/\[//g;s/\]//g;s/"//g;s/ Result //g'

