#!/usr/bin/python3

import re

me    = "David Robson"
file1 = open('/home/dave/Documents/chess/MyGames/MyGames.pgn', 'r')
Lines = file1.readlines()
  
count = 0
# Strips the newline character
for line in Lines:

    if re.match(r"^\[ *Date .*", line):
        date = line.split('"')[1];

    if re.match(r"^\[ *WhiteElo .*", line):
        whiteELO = line.split('"')[1];

    if re.match(r"^\[ *BlackElo .*", line):
        blackELO = line.split('"')[1];

    if re.match(r"^\[ *Result .*", line):
        result = line.split('"')[1];

    if re.match(r"^\[ *Opening .*", line):
        opening = line.split('"')[1];

    if re.match(r"^\[ *Variation.*", line):
        variation = line.split('"')[1];

    if re.match(r"^\[ *White .*", line):
        player = line.split('"')[1];
        if player != me:
           opponent = player;
           colour = "BLACK";

    if re.match(r"^\[ *Black .*", line):
        player = line.split('"')[1];
        if player != me:
           opponent = player;
           colour = "WHITE";

    if re.match(r"^ *1\. *[a-zA-Z].*", line):
        if colour == "WHITE":
           playerRating = blackELO
           myRating = whiteELO
        if colour == "BLACK":
           playerRating = whiteELO
           myRating = blackELO
        if result == "1/2-1/2":
           result = "DREW"
        if result == "1-0" and colour == "WHITE":
           result = "WON"
        if result == "1-0" and colour == "BLACK":
           result = "LOST"
        if result == "0-1" and colour == "WHITE":
           result = "LOST"
        if result == "0-1" and colour == "BLACK":
           result = "WON"

        print(date,opponent.ljust(22),result.ljust(4),colour,myRating.rjust(4),playerRating.rjust(4),opening.ljust(12),variation)
        date = opponent = result = colour = myRating = platerRating = "?"
        opening = variation = " "

file1.close()
